### ISSUE TITLE
New `MoBends_1.12.2-1.1.0-28.09.21.jar` must be disabled on server

### ISSUE THREAD

**Issue by ubergarm** [iwoplaza/MoBends#248]
**Describe the bug**

Not technically a *bug* as MoBends is technically a client side mod, but earlier versions would still run okay even if on the server. The new `MoBends_1.12.2-1.1.0-28.09.21.jar` however prevents the server from starting. Just want to report here in case people updating run into this.

The work-around is to rename the jar to `.jar.disabled` or to just delete the `.jar` file from the server pack. Not a biggie!

**To Reproduce**
1. Update from `MoBends_1.12.2-1.0.0-beta-20.06.20.jar` to `MoBends_1.12.2-1.1.0-28.09.21.jar` files on a Forge server. It will now prevent the server from starting. 

**Expected behavior**
Previous versions of MoBends would not prevent the server from loading even when the jar file was present.

**Context (please complete the following information):**
 - Minecraft 1.12.2
 - Forge `forge-1.12.2-14.23.5.2855.jar`
 - Mo' Bends version `MoBends_1.12.2-1.1.0-28.09.21.jar`
 - For a full mod list see [Rotten Economy Modpack v0.84](https://www.curseforge.com/minecraft/modpacks/rotten-economy)
 
**Additional context**
Here is the stack trace from `debug.log` that the server prints out. 
```
[21:01:38] [Server thread/TRACE] [FML]: Sending event FMLInitializationEvent to mod mobends
[21:01:38] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mo' Bends (mobends)

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourceManagerReloadListener
        at goblinbob.mobends.core.addon.Addons.registerAddon(Addons.java:29) ~[Addons.class:1.1.0-28.09.21]
        at goblinbob.mobends.core.addon.AddonHelper.registerAddon(AddonHelper.java:13) ~[AddonHelper.class:1.1.0-28.09.21]
        at goblinbob.mobends.standard.main.MoBends.init(MoBends.java:52) ~[MoBends.class:1.1.0-28.09.21]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2855.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
```

**Comment by iwoplaza** [comment]
Thank you for the report! This was an oversight on my part, sorry for the inconvenience. This is going to get fixed in the next update 😄
